version: "3.8"

services:
  backend:
    build:
      context: ./api  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env  
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "3000:80"  
    depends_on:
      - backend
    restart: unless-stopped
